name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Testing Secrets
      run:
        if [ "$DEVOPS" == "dEVOPSHINT"]
        then
          echo "Got our Secret"
        fi
      env: 
        DEVOPS: $({secrets.SECRETS_TOKEN})
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
